# LAD construction variables

# Geant 4 GUI (0) or terminal (1)
G4GUI 0

# MultiThread (0 MultiThread, 1 simple thread-better for debbuging)
MultiTh 1

# Generator (0: scan LAD, 1: raster 2: LUND 3:DISgen)
GeneratorCase 3

# Scan particle (proton, electron, geantino)
ScanParticle proton

# Momentum of the particle (Scan case) (in MeV)
ScanMomentumParticle 300

# The location of DIS Generator Root File
DISrootFile /w/hallc-scshelf2102/c-lad/haocen/Deuteron_DIS/GEMC/generator/10.2/tagged_full/PRC/test_band_tagged_full_PRC_E10.2GeV_recp.root

# HODOSCOPE construction

# WALLS ANGLES
# Angles of the hodoscope side walls  are given wrt to the central wall
# left wall is a double wall (larger angle)
# right wall is the single wall (smaller angle)

centralWallAngle 127 #deg    default 127 deg

# angles in absolute value
leftWallAngle 23    #deg     default 23 deg
rightWallAngle 23   #deg     default 23 deg


# WALL POSITIONS
# position of the walls are from the center of the Hall
# to the front face of the wall. Side wall distance is wrt to the
# central wall

centralWallDistance 523  # cm   default 523 cm
leftWallDistance 92      # cm   default  92 cm
rightWallDistance 92     # cm   default  92 cm

# Hodo alignment corrections.
# dx/dy/dz: m; dPitch/dYaw/dRoll: deg.
#   +Pitch -> counter-clockwise rotation about X
#   +Yaw -> counter-clockwise rotation about Y
#   +Roll -> counter-clockwise rotation about Z
# wall 0: left, wall 1: central, wall 2: right.
# layer follows copy number: wall*10000 + layer*100 + bar.

#          wall  layer   dx         dy          dz         dPitch       dYaw        dRoll
HodoAlign   0     1      0.01463    -0.00182    0.03230    -0.2848      -0.1800     -0.0547
HodoAlign   2     0      0.00339    0.00510     -0.0016    0.0877       0.1046      -0.0077
HodoAlign   1     0      0.01538    0.00544     0.04197    -0.4985      -0.2597     -0.3552
HodoAlign   0     0      0.03429    0.00002     0.04123    -0.4736      0.1938      -0.1558
HodoAlign   1     1      0.02232    0.01303     0.02883    -0.1922      0.0012      -0.3776
