# LAD construction variables

# Geant 4 GUI (0) or terminal (1)
G4GUI 0

# MultiThread (0 MultiThread, 1 simple thread-better for debbuging)
MultiTh 1

# Generator (0: scan LAD, 1: raster 2: LUND 3:DISgen)
GeneratorCase 3

# Scan particle (proton, electron, geantino)
ScanParticle proton

# Momentum of the particle (Scan case) (in MeV)
ScanMomentumParticle 300

# The location of DIS Generator Root File
DISrootFile /w/hallc-scshelf2102/c-lad/haocen/Deuteron_DIS/GEMC/generator/10.2/tagged_full/PRC/test_band_tagged_full_PRC_E10.2GeV_recp.root

# HODOSCOPE construction

# WALLS ANGLES
# Angles of the hodoscope side walls  are given wrt to the central wall
# left wall is a double wall (larger angle)
# right wall is the single wall (smaller angle)

centralWallAngle 127 #deg    default 127 deg

# angles in absolute value
leftWallAngle 23    #deg     default 23 deg
rightWallAngle 23   #deg     default 23 deg


# WALL POSITIONS
# position of the walls are from the center of the Hall
# to the front face of the wall. Side wall distance is wrt to the
# central wall

centralWallDistance 523  # cm   default 523 cm
leftWallDistance 92      # cm   default  92 cm
rightWallDistance 92     # cm   default  92 cm
